# Generated by Django 3.1.7 on 2022-07-31 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='action',
            field=models.IntegerField(default=1),
        ),
    ]
